apiVersion: apps/v1
kind: Deployment
metadata:
  name: ToyTrexapi
  labels:
    stack: ToyTrex
spec:
  replicas: 1
  template:
    metadata:
      labels:        
        stack: ToyTrex
    spec:
      restartPolicy: Always
      containers:
      - name: ToyTrex-api
        image: subashtest.azurecr.io/toytrex/middlelayerapi:12345               
        ports:        
          containerPort: 8080
        resources: {}
        stdin: true
        tty: true
      volumes:
      - name: vars-config-volume
        configMap:
          name: vars-config
      - name: vars-secret-volume
        secret:
          secretName: vars-secret